FROM arm64v8/ubuntu:16.04

ENV LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/
RUN mkdir /cudaSamples

CMD /cudaSamples/deviceQuery

#
# Run with:
#  docker run --device=... -v /usr/local/cuda-x/samples/1_Utilities/deviceQuery:/cudaSamples/ -v /usr/lib/aarch64-linux-gnu/:/usr/lib/aarch64-linux-gnu/ device-query
#
